### ISSUE TITLE
Install Issues on OSX

### ISSUE THREAD

**Issue by j-c-c** [mjo22/cryojax#210]
Hi,

I ran into some trouble installing `cryojax` with the `test` dependencies on OSX (detailed below).

Which operating system and Python version are you using?
- macOS 14.4.1
- python 3.11

Which version of this project are you using?
- v0.2.3, `grid-search` branch

What did you do?
- `git clone https://github.com/mjo22/cryojax`
- `python -m pip install ".[test]"`

What did you expect to see?
- "Successfully installed cryojax-0.2.3"

What did you see instead?
```
Processing /Users/carmichael/Work/cryojax
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: equinox>=0.11.0 in /Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages (from cryojax==0.2.3) (0.11.4)
Requirement already satisfied: jax in /Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages (from cryojax==0.2.3) (0.4.26)
Requirement already satisfied: jaxlib in /Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages (from cryojax==0.2.3) (0.4.26)
Requirement already satisfied: jaxtyping>=0.2.23 in /Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages (from cryojax==0.2.3) (0.2.28)
Requirement already satisfied: lineax in /Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages (from cryojax==0.2.3) (0.0.5)
Requirement already satisfied: mrcfile in /Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages (from cryojax==0.2.3) (1.5.0)
Requirement already satisfied: pandas in /Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages (from cryojax==0.2.3) (2.2.2)
Requirement already satisfied: starfile in /Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages (from cryojax==0.2.3) (0.5.6)
Requirement already satisfied: typing-extensions>=4.5.0 in /Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages (from cryojax==0.2.3) (4.11.0)
Requirement already satisfied: gemmi in /Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages (from cryojax==0.2.3) (0.6.5)
Collecting pycistem (from cryojax==0.2.3)
  Using cached pycistem-0.3.1.tar.gz (16.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/jv/3hrz__0x419bjk70hwzm_pbc0000gp/T/pip-build-env-xp2r7coo/overlay/lib/python3.11/site-packages/hatchling/build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/jv/3hrz__0x419bjk70hwzm_pbc0000gp/T/pip-build-env-xp2r7coo/overlay/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 147, in build
          build_hook.initialize(version, build_data)
        File "/private/var/folders/jv/3hrz__0x419bjk70hwzm_pbc0000gp/T/pip-install-ip8qlsua/pycistem_9ae9fde4e3ab4bee963f77a3cda8b100/hatch_build.py", line 88, in initialize
          build(t)
        File "/private/var/folders/jv/3hrz__0x419bjk70hwzm_pbc0000gp/T/pip-install-ip8qlsua/pycistem_9ae9fde4e3ab4bee963f77a3cda8b100/hatch_build.py", line 45, in build
          wxflags = subprocess.run([wx_config, "--cxxflags"], stdout=subprocess.PIPE).stdout.decode("utf-8")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/carmichael/opt/miniconda3/envs/aspire-cryojax-env/lib/python3.11/subprocess.py", line 1953, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'wx-config'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by mjo22** [comment]
Thank you for the bug report! The issue with the test dependencies is due to [`pycistem`](https://github.com/jojoelfe/pycistem), which only provides linux wheels. We need to think about a good solution to this.

The second issue seems to be an installation issue with jax. This issue seems relevant: https://github.com/google/jax/discussions/19343. I currently have a CPU-only JAX install working on my M2 mac with python 3.10. I would expect the solution to be simpler than the solution in that thread though—if I’m not mistaken these instructions seem to say they release wheels on PyPI for your machine specs?

https://jax.readthedocs.io/en/latest/installation.html#supported-platforms.

**Comment by mjo22** [comment]
This should be fixed!
